version: "3.9"
services:
  mysql8_omc:
    container_name: omc
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omc
    volumes:
      - sql_omc:/var/lib/mysql
    restart: always

volumes:
  sql_omc:
    name: sql_omc
